git clone ssh://git@bitbucket.gfs.com/naoo/apache-config.git
git clone ssh://git@bitbucket.gfs.com/naoo/backup-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/cart-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/circuit-breaker-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/cloud-functions.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-exclusion-sap-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-exclusion-sap-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-inclusion-sap-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-inclusion-sap-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-material-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-mygfs-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-mygfs-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/customer-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/deliveryschedule-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/downscaler.git
git clone ssh://git@bitbucket.gfs.com/naoo/elasticsearch-index-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/elasticsearch-integration-tests.git
git clone ssh://git@bitbucket.gfs.com/naoo/elasticsearch-monitoring.git
git clone ssh://git@bitbucket.gfs.com/naoo/embedded-elasticsearch.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcd-backup-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcd-data-admin.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcp-configuration.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcp-tf-k8s-spinnaker.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcp-tf-naoo-cluster.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcp-tf-naoo-devops.git
git clone ssh://git@bitbucket.gfs.com/naoo/gcp-tf-naoo-security.git
git clone ssh://git@bitbucket.gfs.com/naoo/Forkgfs-pipeline-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/go-bot.git
git clone ssh://git@bitbucket.gfs.com/naoo/graceful-shutdown-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/httpbin.git
git clone ssh://git@bitbucket.gfs.com/naoo/inventory-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/jwt-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/kibana-config.git
git clone ssh://git@bitbucket.gfs.com/naoo/list-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/local-dev-support.git
git clone ssh://git@bitbucket.gfs.com/naoo/logging-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/material-ham-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/material-ham-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/material-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/material-mygfs-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/material-mygfs-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/message-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-devops.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-it-support.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-java.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-jenkins-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-jmeter.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-utils.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-web.git
git clone ssh://git@bitbucket.gfs.com/naoo/naoo-web-bff.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-api-gateway.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-guide-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-guide-mygfs-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-guide-mygfs-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-guide-sap-index-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-guide-sap-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/order-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/organization-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/parent-pom.git
git clone ssh://git@bitbucket.gfs.com/naoo/performance-tests.git
git clone ssh://git@bitbucket.gfs.com/naoo/pre-prod-credentials.git
git clone ssh://git@bitbucket.gfs.com/naoo/price-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/prod-credentials.git
git clone ssh://git@bitbucket.gfs.com/naoo/product-load-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/product-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/punchout-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/sanitization-library.git
git clone ssh://git@bitbucket.gfs.com/naoo/search-config.git
git clone ssh://git@bitbucket.gfs.com/naoo/search-index-reverter.git
git clone ssh://git@bitbucket.gfs.com/naoo/spinnaker-pipelines.git
git clone ssh://git@bitbucket.gfs.com/naoo/user-service.git
git clone ssh://git@bitbucket.gfs.com/naoo/wiremock-config.git